//! `known_hosts` parsing, matching, and verdicts.
//!
//! Fixtures are generated by real `ssh-keygen` (including `-H` for the hashed
//! entry) rather than hand-written, so these tests check agreement with
//! OpenSSH rather than agreement with our own encoder. Only public keys are
//! committed — an SSH client's repo is the last place to keep private ones.

use std::path::PathBuf;

use tern_core_ssh::{HostKeyVerdict, KnownHostsFile};

use russh::keys::ssh_key::PublicKey;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/known_hosts")
}

fn key(name: &str) -> PublicKey {
    let raw = std::fs::read_to_string(fixtures().join(name)).expect("read fixture key");
    PublicKey::from_openssh(raw.trim()).expect("parse fixture key")
}

/// Copy a fixture into a scratch file so write tests never mutate the fixture.
fn scratch(from: Option<&str>, tag: &str) -> PathBuf {
    use std::sync::atomic::{AtomicU32, Ordering};
    static N: AtomicU32 = AtomicU32::new(0);
    let dir = std::env::temp_dir().join(format!(
        "tern-kh-{}-{}-{}",
        std::process::id(),
        tag,
        N.fetch_add(1, Ordering::Relaxed)
    ));
    std::fs::create_dir_all(&dir).expect("create scratch dir");
    let path = dir.join("known_hosts");
    if let Some(name) = from {
        std::fs::copy(fixtures().join(name), &path).expect("seed scratch file");
    }
    path
}

fn plain() -> KnownHostsFile {
    KnownHostsFile::at(fixtures().join("plain"))
}

#[test]
fn exact_hostname_is_trusted() {
    let verdict = plain()
        .verify("plain.example.com", 22, &key("key_a.pub"))
        .expect("verify");
    assert_eq!(verdict, HostKeyVerdict::Trusted);
}

#[test]
fn unknown_host_is_first_contact() {
    let verdict = plain()
        .verify("never-seen.example.com", 22, &key("key_a.pub"))
        .expect("verify");
    assert_eq!(verdict, HostKeyVerdict::Unknown);
}

#[test]
fn a_different_key_for_a_known_host_is_changed() {
    let verdict = plain()
        .verify("plain.example.com", 22, &key("key_b.pub"))
        .expect("verify");
    match verdict {
        HostKeyVerdict::Changed {
            recorded_algorithm,
            recorded_fingerprint,
            line,
        } => {
            assert_eq!(recorded_algorithm, "ssh-ed25519");
            // The recorded fingerprint has to reach the UI — showing the user
            // what was expected vs offered is the whole point of the dialog.
            assert!(recorded_fingerprint.starts_with("SHA256:"));
            assert!(line > 0);
        }
        other => panic!("expected Changed, got {other:?}"),
    }
}

#[test]
fn a_different_algorithm_is_unknown_not_changed() {
    // A host recorded under ed25519 that now offers RSA has simply never been
    // recorded under RSA. Calling that "changed" would train users to click
    // through the scariest dialog in the app.
    let verdict = plain()
        .verify("plain.example.com", 22, &key("key_rsa.pub"))
        .expect("verify");
    assert_eq!(verdict, HostKeyVerdict::Unknown);
}

#[test]
fn non_default_ports_use_the_bracket_form() {
    let f = plain();
    assert_eq!(
        f.verify("alt.example.com", 2222, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
    // The same host on the default port is a different entry entirely.
    assert_eq!(
        f.verify("alt.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Unknown
    );
}

#[test]
fn wildcard_patterns_match() {
    let verdict = plain()
        .verify("anything.wild.example.com", 22, &key("key_a.pub"))
        .expect("verify");
    assert_eq!(verdict, HostKeyVerdict::Trusted);
}

#[test]
fn comma_separated_patterns_all_match() {
    let f = plain();
    for host in ["one.example.com", "two.example.com"] {
        assert_eq!(
            f.verify(host, 22, &key("key_a.pub")).expect("verify"),
            HostKeyVerdict::Trusted,
            "{host} should match its comma-separated entry"
        );
    }
}

#[test]
fn revoked_entries_are_refused_even_with_a_matching_key() {
    // This is the case russh's own parser gets wrong: the @revoked marker
    // shifts field positions, so the line never matches and the key presents
    // as merely unknown — a friendly prompt for a key the admin revoked.
    let verdict = plain()
        .verify("revoked.example.com", 22, &key("key_a.pub"))
        .expect("verify");
    assert!(
        matches!(verdict, HostKeyVerdict::Revoked { .. }),
        "expected Revoked, got {verdict:?}"
    );
}

#[test]
fn cert_authority_lines_do_not_masquerade_as_host_keys() {
    // Certificate auth is deferred, but a @cert-authority line must not be
    // read as a mismatched host key and trigger the changed-key alarm.
    let verdict = plain()
        .verify("ca.example.com", 22, &key("key_b.pub"))
        .expect("verify");
    assert_eq!(verdict, HostKeyVerdict::Unknown);
}

#[test]
fn hashed_entries_match() {
    // Fixture written by `ssh-keygen -H`, so this proves interop with
    // OpenSSH's HMAC-SHA1 construction, not just self-consistency.
    let f = KnownHostsFile::at(fixtures().join("hashed"));
    assert_eq!(
        f.verify("hashme.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
    assert_eq!(
        f.verify("other.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Unknown
    );
}

#[test]
fn a_malformed_line_does_not_poison_the_file() {
    // The plain fixture ends with a garbage line. Every assertion above still
    // passing is the real proof, but state it directly too.
    let verdict = plain()
        .verify("plain.example.com", 22, &key("key_a.pub"))
        .expect("verify");
    assert_eq!(verdict, HostKeyVerdict::Trusted);
    // And the entry list simply omits it.
    let entries = plain().entries().expect("entries");
    assert!(entries.len() >= 7);
}

#[test]
fn missing_file_knows_no_hosts() {
    let f = KnownHostsFile::at(scratch(None, "missing"));
    assert_eq!(
        f.verify("anything", 22, &key("key_a.pub")).expect("verify"),
        HostKeyVerdict::Unknown
    );
}

#[test]
fn learn_then_verify_round_trips() {
    let f = KnownHostsFile::at(scratch(None, "learn"));
    f.learn("new.example.com", 22, &key("key_a.pub"), false)
        .expect("learn");
    assert_eq!(
        f.verify("new.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
    // And a different key for it is now correctly alarming.
    assert!(matches!(
        f.verify("new.example.com", 22, &key("key_b.pub"))
            .expect("verify"),
        HostKeyVerdict::Changed { .. }
    ));
}

#[test]
fn learn_round_trips_on_a_non_default_port() {
    let f = KnownHostsFile::at(scratch(None, "learn-port"));
    f.learn("gw.example.com", 2222, &key("key_a.pub"), false)
        .expect("learn");
    assert_eq!(
        f.verify("gw.example.com", 2222, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
}

#[test]
fn learn_hashed_round_trips() {
    let f = KnownHostsFile::at(scratch(None, "learn-hashed"));
    f.learn("secret.example.com", 22, &key("key_a.pub"), true)
        .expect("learn");
    let raw = std::fs::read_to_string(f.path()).expect("read");
    assert!(raw.starts_with("|1|"), "entry should be hashed: {raw}");
    assert!(
        !raw.contains("secret.example.com"),
        "hashing must not leave the hostname in the file"
    );
    assert_eq!(
        f.verify("secret.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
}

#[test]
fn learn_does_not_glue_onto_a_file_missing_its_final_newline() {
    let path = scratch(None, "nonewline");
    let existing = std::fs::read_to_string(fixtures().join("plain")).expect("read fixture");
    std::fs::write(&path, existing.trim_end()).expect("write without trailing newline");

    let f = KnownHostsFile::at(&path);
    f.learn("appended.example.com", 22, &key("key_b.pub"), false)
        .expect("learn");

    // Both the pre-existing last entry and the new one must still parse.
    assert_eq!(
        f.verify("appended.example.com", 22, &key("key_b.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
    assert_eq!(
        f.verify("plain.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
}

#[test]
fn remove_clears_the_changed_state() {
    // The documented recovery path: a changed key is never "trust anyway" in
    // place — you remove the entry, then reconnect and get first contact.
    let f = KnownHostsFile::at(scratch(Some("plain"), "remove"));
    assert!(matches!(
        f.verify("plain.example.com", 22, &key("key_b.pub"))
            .expect("verify"),
        HostKeyVerdict::Changed { .. }
    ));

    let removed = f.remove("plain.example.com", 22).expect("remove");
    assert_eq!(removed, 1);

    assert_eq!(
        f.verify("plain.example.com", 22, &key("key_b.pub"))
            .expect("verify"),
        HostKeyVerdict::Unknown
    );
    // Unrelated entries survive.
    assert_eq!(
        f.verify("one.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
}

#[test]
fn import_copies_entries_without_touching_the_source() {
    let dest = KnownHostsFile::at(scratch(None, "import"));
    let source = fixtures().join("plain");
    let before = std::fs::read_to_string(&source).expect("read source");

    let report = dest.import_from(&source).expect("import");
    assert!(report.imported > 0);
    assert_eq!(report.skipped_cert_authority, 1);
    assert_eq!(report.malformed, 1);

    let after = std::fs::read_to_string(&source).expect("read source again");
    assert_eq!(before, after, "import must never modify the source file");

    assert_eq!(
        dest.verify("plain.example.com", 22, &key("key_a.pub"))
            .expect("verify"),
        HostKeyVerdict::Trusted
    );
}

#[test]
fn importing_twice_does_not_duplicate() {
    let dest = KnownHostsFile::at(scratch(None, "import-twice"));
    let source = fixtures().join("plain");
    let first = dest.import_from(&source).expect("first import");
    let second = dest.import_from(&source).expect("second import");

    assert_eq!(second.imported, 0, "re-import should add nothing");
    assert_eq!(second.duplicates, first.imported);
}

#[test]
fn importing_a_missing_source_is_not_an_error() {
    // First run on a machine with no ~/.ssh/known_hosts is normal, not a fault.
    let dest = KnownHostsFile::at(scratch(None, "import-missing"));
    let report = dest
        .import_from(&fixtures().join("does-not-exist"))
        .expect("import");
    assert_eq!(report.total, 0);
    assert_eq!(report.imported, 0);
}
