#!/usr/bin/env bun
// Renders docs/bench/phase0-results.md from docs/bench/results/*.json
// (written by the in-app auto-benchmark via the bench_finish command).

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const RESULTS = "docs/bench/results";
const OUT = "docs/bench/phase0-results.md";

const files = readdirSync(RESULTS).filter((f) => f.endsWith(".json"));
if (files.length === 0) {
  console.error(`no results in ${RESULTS} — run the auto-benchmark first`);
  process.exit(1);
}
const parsed = files.map((f) => JSON.parse(readFileSync(join(RESULTS, f), "utf8")));
const reports = parsed
  .filter((r) => r.rust && r.js && r.scenario)
  .sort((a, b) => a.scenario.localeCompare(b.scenario) || a.chunk_max - b.chunk_max);
const readOpt = (name) => {
  try {
    return JSON.parse(readFileSync(join(RESULTS, name), "utf8"));
  } catch {
    return null;
  }
};
const core = readOpt("core.json");
const headless = readOpt("headless.json");

const mbps = (bytes, ms) => (ms > 0 ? bytes / 1048576 / (ms / 1000) : 0);
const fmt = (n, d = 1) => (n === undefined || n === null ? "—" : Number(n).toFixed(d));

const row = (r) => {
  const parsed = mbps(r.js.parsed_bytes, r.js.wall_ms);
  const rust = mbps(r.rust.bytes_in, r.js.wall_ms);
  const lossless = r.rust.newlines_in === r.js.js_newlines ? "✅" : "❌";
  return (
    `| ${r.scenario} | ${r.chunk_max / 1024}K/${r.tick_ms}ms/${r.window_size / 1024}K | ` +
    `${fmt(rust)} | ${fmt(parsed)} | ${r.js.recv_frames} | ` +
    `${(r.js.max_pending_bytes / 1024).toFixed(0)}K | ${r.js.pause_count}/${r.rust.paused_ms}ms | ` +
    `${fmt(r.js.max_stall_ms, 0)} | ` +
    `${r.js.echo_p50_ms !== undefined && r.js.echo_p50_ms !== null ? `${fmt(r.js.echo_p50_ms, 2)}/${fmt(r.js.echo_p95_ms, 2)}/${fmt(r.js.echo_max_ms, 2)}` : "—"} | ` +
    `${lossless} |`
  );
};

const env = reports[0];
const cat = reports.find((r) => r.scenario === "cat100mb" && r.chunk_max === 65536);
const echo = reports.find((r) => r.scenario === "echo");
const anyLoss = reports.some((r) => r.rust.newlines_in !== r.js.js_newlines);
const catMbps = cat ? mbps(cat.js.parsed_bytes, cat.js.wall_ms) : 0;

const md = `# Phase 0 — Terminal data-path benchmark results

*Generated by \`scripts/bench-report.mjs\` from \`docs/bench/results/*.json\`.
Reproduce with \`scripts/sshd-rig.sh up\` then
\`TERN_BENCH=auto TERN_BENCH_EXIT=1 TERN_SSH_KEY=$PWD/.rig/ssh/id_ed25519 bun tauri dev\`.*

Path under test (ADR-0011): russh channel → bounded pump → coalescer
(tick/size) → **raw** Tauri \`Channel\` (\`InvokeResponseBody::Raw\`) →
\`xterm.write()\` with pending-byte watermarks (pause 384K / resume 64K)
driving pause/resume commands back into the SSH window.

Renderer: **${env.renderer}** · server: **${env.server}** (loopback Docker rig)

| scenario | chunk/tick/window | rust-in MB/s | parsed MB/s | frames | max pending | pauses/paused | max stall ms | echo p50/p95/max ms | lossless |
|---|---|---|---|---|---|---|---|---|---|
${reports.map(row).join("\n")}

*rust-in/parsed MB/s use the same JS wall clock, so rust-in ≈ how fast the SSH
side produced during the scenario, parsed = what xterm consumed end-to-end.
Lossless = newline tallies taken independently in Rust (coalescer input) and
JS (before \`write\`) match exactly.*

## Verdict vs Phase 0 exit criteria

- **Zero dropped output:** ${anyLoss ? "❌ loss detected — see table" : "✅ every scenario lossless (independent Rust/JS newline tallies equal)"}
- **Perceived echo p95 < 16 ms:** ${echo ? `${fmt(echo.js.echo_p95_ms, 2)} ms → ${echo.js.echo_p95_ms < 16 ? "✅" : "❌"}` : "not measured"} (p50 ${echo ? fmt(echo.js.echo_p50_ms, 2) : "—"} ms, parse-complete definition, ${echo?.js.echo_samples ?? 0} keystrokes)
- **End-to-end sustained ≥ 20 MB/s:** cat100mb ${fmt(catMbps)} MB/s → ${catMbps >= 20 ? "✅" : "❌"}
- **UI stays interactive (< 250 ms stalls):** ${reports.every((r) => (r.js.max_stall_ms ?? 0) < 250) ? "✅" : "❌ see table"}

Escape-hatch gates (wgpu investigation — ADR-0005): end-to-end < 10 MB/s,
echo p95 > 32 ms, reproducible loss, or > 500 ms stalls.
**${anyLoss || catMbps < 10 || (echo?.js.echo_p95_ms ?? 99) > 32 ? "GATE TRIPPED — investigate" : "No gate tripped — the cheap path holds."}**

## Headless slice (CI-runnable — \`scripts/bench-ci.sh\`, no webview)

${core ? core.results.map((r) => `- **${r.name}** (bench_sink: SSH → pump → coalescer → sink): ${r.mbps.toFixed(1)} MB/s, ${r.newlines.toLocaleString("en-US")} newlines, complete=${r.complete}`).join("\n") : "- core: not recorded"}
${core ? `- core floor ≥ ${core.core_floor_mbps ?? 80} MB/s: ${(core.core_floor_ok ?? core.core_floor_80mbps) ? "✅" : "❌"} · lossless: ${core.lossless ? "✅" : "❌"}` : ""}
${headless ? `- **@xterm/headless consumer** (same watermark logic over a real backpressured pipe): ${headless.parsed_mbps} MB/s parsed, ${headless.pauses} pauses, floor ≥ ${headless.floor_mbps ?? 30} MB/s: ${(headless.floor_ok ?? headless.floor_30mbps) ? "✅" : "❌"}` : "- headless: not recorded"}

## Caveats

- Loopback rig: network jitter excluded by design — the component under test
  is russh→IPC→xterm, not the wire. Real-host echo numbers will add RTT.
- Echo t₁ = xterm parse-complete (write callback); GPU paint completion is not
  reliably observable and is excluded (rAF-gap stall metric bounds it).
- While the SSH window is paused, outbound keystrokes queue behind the stalled
  session loop (russh caveat); \`yes10s\` pause totals above put a bound on it.
- WebKitGTK (Linux) untested until Phase 1 multi-distro testing.
`;

writeFileSync(OUT, md);
console.log(`wrote ${OUT} from ${files.length} result files`);
